# Make tmux use 256-color and advertise truecolor
set-option -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'dalejung/tmux-select-pane-no-wrap'

# tmux-resurrect config
set -g @resurrect-capture-pane-contents 'on'

# tmux-continuum config
set -g @continuum-restore 'on'    # restore on tmux start
set -g @continuum-save-interval '15' # auto-save every 15 minutes

# Initialize TMUX plugin manager
run '~/.tmux/plugins/tpm/tpm'



# Prefix key (optional)
# set -g prefix C-a
# unbind C-b
# bind C-a send-prefix

# Optional: Alt+hjkl navigation without prefix
bind -n M-h run-shell "#{select_pane_no_wrap} L"
bind -n M-j run-shell "#{select_pane_no_wrap} D"
bind -n M-k run-shell "#{select_pane_no_wrap} U"
bind -n M-l run-shell "#{select_pane_no_wrap} R"

# Resize panes quickly
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Split panes
bind | split-window -h
bind - split-window -v
bind x kill-pane

# Quick pane switching
bind \; last-pane

# Synchronize panes
bind S setw synchronize-panes on
bind s setw synchronize-panes off
